seed: 1
num_worker: 4
work_dir: ./work_dir/table_tennis/cs/SkateFormer_b_2D_20250305_01/

phase: train

# feeder
feeder: feeders.feeder_table_tennis_2D.Feeder
train_feeder_args:
  data_path: ./data/table_tennis_2D/table_tennis.npz
  split: train
  data_type: b
  debug: False
  window_size: 32 # 64 32 16 8
  p_interval: [0.5, 1]
  aug_method: '' # '123489'
  intra_p: 0.0 # 0.5 Intra-instance Augmentation
  inter_p: 0.0 # 0.2 Inter-instance Augmentation
  thres: 32 # 64
  uniform: True
  partition: True

test_feeder_args:
  data_path: ./data/table_tennis_2D/table_tennis.npz
  split: test
  data_type: b
  window_size: 32 # 64
  p_interval: [0.95]
  thres: 32 # 64
  uniform: True
  partition: True
  debug: False

# model
model: model.SkateFormer_2D.SkateFormer_
model_args:
  num_classes: 8 # 60
  num_people: 1 # 2
  num_points: 16 #24
  kernel_size: 7
  num_heads: 32
  attn_drop: 0.5 # 0.5
  head_drop: 0.0
  rel: True
  drop_path: 0.2 # 0.2
  type_1_size: [4, 4] # [8, 8] # 需要小於window_size//4
  type_2_size: [4, 8] # [8, 12]
  type_3_size: [4, 4] # [8, 8]
  type_4_size: [4, 8] # [8, 12]
  mlp_ratio: 4.0 # 4.0
  index_t: True

#optim
optimizer: AdamW
weight_decay: 0.1
lr_scheduler: cosine
base_lr: 1e-3 # 1e-3
min_lr: 1e-5 # 1e-5
warmup_lr: 1e-7 # 1e-7
warmup_prefix: False
warm_up_epoch: 25 # 25

# training
device: [0]
batch_size: 1 # 128
test_batch_size: 1 # 128
num_epoch: 500 # 500
nesterov: True
grad_clip: True
grad_max: 1.0
loss_type: LSCE #LSCE
